/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.javanutrifacts;

import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author johnn
 */
public class frmBaseAlimentos extends javax.swing.JFrame {

    
    DefaultTableModel modelo = new DefaultTableModel();
    
    public frmBaseAlimentos() {
        initComponents();
        this.setTitle("NUTRIFACTS");
        this.setLocationRelativeTo(this);
        modelo.setColumnCount(6);
        modelo.setRowCount(0);
        String[] titulo={"NOMBRE","CLASIFICACION","ORIGEN","BENEFICIOS","RECOMENDACIONES","PREPARACION"};
        modelo.setColumnIdentifiers(titulo);
        tblDatos.setModel(modelo);
        DisenoTabla();
        Font();
        insertaIconos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();
        btnRetornar = new javax.swing.JButton();
        btnNuevoAlimento = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblAlimento = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(720, 720));
        setMinimumSize(new java.awt.Dimension(720, 720));
        setPreferredSize(new java.awt.Dimension(720, 720));
        setSize(new java.awt.Dimension(720, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setMaximumSize(new java.awt.Dimension(400, 400));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(400, 400));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(400, 400));

        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDatos.setAutoscrolls(false);
        tblDatos.setMaximumSize(new java.awt.Dimension(490, 100));
        tblDatos.setMinimumSize(new java.awt.Dimension(490, 100));
        tblDatos.setPreferredSize(new java.awt.Dimension(490, 100));
        jScrollPane1.setViewportView(tblDatos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 25, 500, -1));

        btnRetornar.setText("RETORNAR");
        btnRetornar.setMaximumSize(new java.awt.Dimension(150, 50));
        btnRetornar.setMinimumSize(new java.awt.Dimension(150, 50));
        btnRetornar.setPreferredSize(new java.awt.Dimension(150, 50));
        btnRetornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetornarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRetornar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, -1, -1));

        btnNuevoAlimento.setText("NUEVO");
        btnNuevoAlimento.setMaximumSize(new java.awt.Dimension(150, 50));
        btnNuevoAlimento.setMinimumSize(new java.awt.Dimension(150, 50));
        btnNuevoAlimento.setPreferredSize(new java.awt.Dimension(150, 50));
        btnNuevoAlimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoAlimentoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevoAlimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 25, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "VER ALIMENTO", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAlimento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblAlimento.setMaximumSize(new java.awt.Dimension(250, 250));
        lblAlimento.setMinimumSize(new java.awt.Dimension(250, 250));
        lblAlimento.setPreferredSize(new java.awt.Dimension(250, 250));
        jPanel1.add(lblAlimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 180, 180));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 410, 180));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 650, 230));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetornarActionPerformed
        msg("Esta saliendo de la base de datos de alimentos...");
        this.dispose();
    }//GEN-LAST:event_btnRetornarActionPerformed

    private void btnNuevoAlimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoAlimentoActionPerformed
        frmRegistroAlimentos fra = new frmRegistroAlimentos();
        fra.setVisible(true);
    }//GEN-LAST:event_btnNuevoAlimentoActionPerformed

    void msg (String msg){
        JOptionPane.showMessageDialog(null, msg);
    }
    
    /**
     * @param args the command line arguments
     */
    
    void DisenoTabla(){
        tblDatos.getTableHeader().setFont(new Font("SansSerif", Font.BOLD, 10));
        
        tblDatos.getColumnModel().getColumn(0).setPreferredWidth(40);
        tblDatos.getColumnModel().getColumn(1).setPreferredWidth(80);
        tblDatos.getColumnModel().getColumn(2).setPreferredWidth(40);
        tblDatos.getColumnModel().getColumn(3).setPreferredWidth(60);
        tblDatos.getColumnModel().getColumn(4).setPreferredWidth(100);
        tblDatos.getColumnModel().getColumn(5).setPreferredWidth(80);
        
        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        renderer.setHorizontalAlignment(SwingConstants.CENTER);
        tblDatos.getColumnModel().getColumn(0).setCellRenderer(renderer);
        tblDatos.getColumnModel().getColumn(1).setCellRenderer(renderer);
        tblDatos.getColumnModel().getColumn(2).setCellRenderer(renderer);
        tblDatos.getColumnModel().getColumn(3).setCellRenderer(renderer);
        tblDatos.getColumnModel().getColumn(4).setCellRenderer(renderer);
        tblDatos.getColumnModel().getColumn(5).setCellRenderer(renderer);
        
    }
    void Font(){
        btnNuevoAlimento.setFont(new Font("SansSerif", Font.BOLD, 11));
        btnRetornar.setFont(new Font("SansSerif", Font.BOLD, 11));
    }
    
    void insertaIconos(){
        ImageIcon rGuardar = new ImageIcon("icons/Guardar.png");
        ImageIcon rRetornar = new ImageIcon("icons/Retornar.png");
        Icon iGuardar = new ImageIcon(rGuardar.getImage().getScaledInstance(25,25,Image.SCALE_DEFAULT));
        Icon iRetornar = new ImageIcon(rRetornar.getImage().getScaledInstance(35,35,Image.SCALE_DEFAULT));
        btnNuevoAlimento.setIcon(iGuardar);
        btnRetornar.setIcon(iRetornar);
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmBaseAlimentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmBaseAlimentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmBaseAlimentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmBaseAlimentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNuevoAlimento;
    private javax.swing.JButton btnRetornar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblAlimento;
    private javax.swing.JTable tblDatos;
    // End of variables declaration//GEN-END:variables
}
