/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.javanutrifacts;

import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.util.HashSet;
import java.util.Set;
import javax.naming.LimitExceededException;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author johnn
 */
public class frmRegistroAlimentos extends javax.swing.JFrame {
    
    /**
     * Creates new form frmRegistroAlimentos
     */
    DefaultTableModel modelo=new DefaultTableModel();
    
    public frmRegistroAlimentos() {
        initComponents();
        this.setTitle("NUTRIFACTS");
        this.setLocationRelativeTo(this);
        this.setLocationRelativeTo(this);
        this.setTitle("Registro de Alimentos");
        //verfoto(lblFondo, "images/Fondo.jpg");
        Limpiar();
        Font();
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblClasificacion = new javax.swing.JLabel();
        lblOrigen = new javax.swing.JLabel();
        lblBeneficios = new javax.swing.JLabel();
        lblRecomendaciones = new javax.swing.JLabel();
        lblPreparacion = new javax.swing.JLabel();
        lblClasificacionImg = new javax.swing.JLabel();
        txtNombreAlimento = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtBeneficios = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtRecomendaciones = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtPreparacion = new javax.swing.JTextArea();
        cmbClasificacion = new javax.swing.JComboBox<>();
        cmbOrigen = new javax.swing.JComboBox<>();
        btnAgregar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnRetornar = new javax.swing.JButton();
        lblOrigenImg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setMaximumSize(new java.awt.Dimension(720, 720));
        setMinimumSize(new java.awt.Dimension(720, 720));
        setPreferredSize(new java.awt.Dimension(720, 720));
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 61, -1, -1));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REGISTRO DE ALIMENTOS");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setPreferredSize(new java.awt.Dimension(600, 50));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 25, -1, -1));

        lblNombre.setText("NOMBRE DE ALIMENTO:");
        lblNombre.setMaximumSize(new java.awt.Dimension(150, 25));
        lblNombre.setMinimumSize(new java.awt.Dimension(150, 25));
        lblNombre.setName(""); // NOI18N
        lblNombre.setPreferredSize(new java.awt.Dimension(150, 25));
        getContentPane().add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        lblClasificacion.setText("CLASIFICACION:");
        lblClasificacion.setMaximumSize(new java.awt.Dimension(150, 25));
        lblClasificacion.setMinimumSize(new java.awt.Dimension(150, 25));
        lblClasificacion.setPreferredSize(new java.awt.Dimension(150, 25));
        getContentPane().add(lblClasificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, -1, -1));

        lblOrigen.setText("ORIGEN:");
        lblOrigen.setMaximumSize(new java.awt.Dimension(150, 25));
        lblOrigen.setMinimumSize(new java.awt.Dimension(150, 25));
        lblOrigen.setPreferredSize(new java.awt.Dimension(150, 25));
        getContentPane().add(lblOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));

        lblBeneficios.setText("BENEFICIOS:");
        lblBeneficios.setMaximumSize(new java.awt.Dimension(150, 25));
        lblBeneficios.setMinimumSize(new java.awt.Dimension(150, 25));
        lblBeneficios.setPreferredSize(new java.awt.Dimension(150, 25));
        getContentPane().add(lblBeneficios, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 250, -1, -1));

        lblRecomendaciones.setText("RECOMENDACIONES:");
        lblRecomendaciones.setMaximumSize(new java.awt.Dimension(150, 25));
        lblRecomendaciones.setMinimumSize(new java.awt.Dimension(150, 25));
        lblRecomendaciones.setPreferredSize(new java.awt.Dimension(150, 25));
        getContentPane().add(lblRecomendaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 325, -1, -1));

        lblPreparacion.setText("PREPARACION:");
        lblPreparacion.setMaximumSize(new java.awt.Dimension(150, 25));
        lblPreparacion.setMinimumSize(new java.awt.Dimension(150, 25));
        lblPreparacion.setPreferredSize(new java.awt.Dimension(150, 25));
        getContentPane().add(lblPreparacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 400, -1, -1));

        lblClasificacionImg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblClasificacionImg.setPreferredSize(new java.awt.Dimension(150, 125));
        getContentPane().add(lblClasificacionImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 100, -1, -1));

        txtNombreAlimento.setPreferredSize(new java.awt.Dimension(200, 25));
        getContentPane().add(txtNombreAlimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 100, -1, -1));

        txtBeneficios.setColumns(33);
        txtBeneficios.setRows(3);
        jScrollPane1.setViewportView(txtBeneficios);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, -1, -1));

        txtRecomendaciones.setColumns(33);
        txtRecomendaciones.setRows(3);
        jScrollPane2.setViewportView(txtRecomendaciones);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 325, -1, -1));

        txtPreparacion.setColumns(33);
        txtPreparacion.setRows(3);
        jScrollPane3.setViewportView(txtPreparacion);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, -1, -1));

        cmbClasificacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Frutas", "Verduras", "Proteinas", "Granos", "Lacteos" }));
        cmbClasificacion.setPreferredSize(new java.awt.Dimension(200, 25));
        cmbClasificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbClasificacionActionPerformed(evt);
            }
        });
        getContentPane().add(cmbClasificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 150, -1, -1));

        cmbOrigen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Asia", "Africa", "Europa", "America del Norte", "America del Sur", "Oceania" }));
        cmbOrigen.setPreferredSize(new java.awt.Dimension(200, 25));
        cmbOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOrigenActionPerformed(evt);
            }
        });
        getContentPane().add(cmbOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 200, -1, -1));

        btnAgregar.setBackground(new java.awt.Color(245, 245, 245));
        btnAgregar.setText("GUARDAR");
        btnAgregar.setMaximumSize(new java.awt.Dimension(175, 50));
        btnAgregar.setMinimumSize(new java.awt.Dimension(175, 50));
        btnAgregar.setPreferredSize(new java.awt.Dimension(175, 50));
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 295, -1, -1));

        btnLimpiar.setBackground(new java.awt.Color(245, 245, 245));
        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.setMaximumSize(new java.awt.Dimension(175, 50));
        btnLimpiar.setMinimumSize(new java.awt.Dimension(175, 50));
        btnLimpiar.setPreferredSize(new java.awt.Dimension(175, 50));
        getContentPane().add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 355, -1, -1));

        btnRetornar.setBackground(new java.awt.Color(245, 245, 245));
        btnRetornar.setText("RETORNAR");
        btnRetornar.setMaximumSize(new java.awt.Dimension(175, 50));
        btnRetornar.setMinimumSize(new java.awt.Dimension(175, 50));
        btnRetornar.setPreferredSize(new java.awt.Dimension(175, 50));
        btnRetornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetornarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRetornar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 415, -1, -1));

        lblOrigenImg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblOrigenImg.setMaximumSize(new java.awt.Dimension(175, 175));
        lblOrigenImg.setMinimumSize(new java.awt.Dimension(175, 175));
        lblOrigenImg.setPreferredSize(new java.awt.Dimension(175, 175));
        getContentPane().add(lblOrigenImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 100, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        
        String nombreA=txtNombreAlimento.getText();
        String beneficios=txtBeneficios.getText();
        String recomendaciones=txtRecomendaciones.getText();
        String preparacion=txtPreparacion.getText();
        String clasificacion=cmbClasificacion.getSelectedItem().toString();
        String origen=cmbOrigen.getSelectedItem().toString();
        modelo.addRow(new Object[]{nombreA,clasificacion,origen,beneficios,recomendaciones,preparacion});
        Limpiar();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void cmbOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOrigenActionPerformed
        String origenC="images/"+cmbOrigen.getSelectedItem().toString()+".jpg";
        verfoto(lblOrigenImg, origenC);
    }//GEN-LAST:event_cmbOrigenActionPerformed

    private void cmbClasificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbClasificacionActionPerformed
        String clasificacionA="images/"+cmbClasificacion.getSelectedItem().toString()+".jpg";
        verfoto(lblClasificacionImg, clasificacionA);
    }//GEN-LAST:event_cmbClasificacionActionPerformed

    private void btnRetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetornarActionPerformed
        msg("Gracias por usar el registro de alimentos");
        this.dispose();
    }//GEN-LAST:event_btnRetornarActionPerformed

    /**
     * @param args the command line arguments
     */
    
    void insertaIcono(JButton btn, String path){
        
    }
    
    void verfoto (JLabel imagen,String cad){
        int ancho =imagen.getWidth();
        int alto =imagen.getHeight();
        ImageIcon foto=new ImageIcon(cad);
        Icon icono=new ImageIcon(foto.getImage().getScaledInstance(ancho,alto,Image.SCALE_DEFAULT));
        imagen.setIcon(icono);
    }
    
    void msg(String m){
    JOptionPane.showMessageDialog(null, m);
    }
    
    void Limpiar(){
    txtNombreAlimento.setText("");
    cmbClasificacion.setSelectedIndex(0);
    cmbOrigen.setSelectedIndex(0);
    txtBeneficios.setText("");
    txtRecomendaciones.setText("");
    txtPreparacion.setText("");
    
    txtNombreAlimento.requestFocus();
    }
    
    
    void Font(){
        //Fuente
        lblNombre.setFont(new Font("SansSerif", Font.BOLD, 14));
        lblClasificacion.setFont(new Font("SansSerif", Font.BOLD, 14));
        lblOrigen.setFont(new Font("SansSerif", Font.BOLD, 14));
        lblBeneficios.setFont(new Font("SansSerif", Font.BOLD, 14));
        lblRecomendaciones.setFont(new Font("SansSerif", Font.BOLD, 14));
        lblPreparacion.setFont(new Font("SansSerif", Font.BOLD, 14));
        
        btnAgregar.setFont(new Font("SansSerif", Font.BOLD, 14));
        btnLimpiar.setFont(new Font("SansSerif", Font.BOLD, 14));
        btnRetornar.setFont(new Font("SansSerif", Font.BOLD, 14));
        
        //Color
        lblNombre.setForeground(new Color(0,102,102));
        lblClasificacion.setForeground(new Color(0,102,102));
        lblOrigen.setForeground(new Color(0,102,102));
        lblBeneficios.setForeground(new Color(0,102,102));
        lblRecomendaciones.setForeground(new Color(0,102,102));
        lblPreparacion.setForeground(new Color(0,102,102));
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRegistroAlimentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRegistroAlimentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRegistroAlimentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRegistroAlimentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRetornar;
    private javax.swing.JComboBox<String> cmbClasificacion;
    private javax.swing.JComboBox<String> cmbOrigen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblBeneficios;
    private javax.swing.JLabel lblClasificacion;
    private javax.swing.JLabel lblClasificacionImg;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblOrigen;
    private javax.swing.JLabel lblOrigenImg;
    private javax.swing.JLabel lblPreparacion;
    private javax.swing.JLabel lblRecomendaciones;
    private javax.swing.JTextArea txtBeneficios;
    private javax.swing.JTextField txtNombreAlimento;
    private javax.swing.JTextArea txtPreparacion;
    private javax.swing.JTextArea txtRecomendaciones;
    // End of variables declaration//GEN-END:variables

    private void setFont(String sansSerif, int BOLD, int i) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
